### ISSUE TITLE
Literature Review Feedback

### ISSUE THREAD

**Issue by ghost** [julia-zhou/MACS30200proj#1]
Great first draft! Next steps:
1) Don't just provide a summary of the literature, but an analytical critique as it applies to your question
2) The title of the "contribution" section is a little unclear. Are you highlighting the contribution of the literature on this topic, or the contribution of your own research project?

**Comment by julia-zhou** [comment]
Hi, the contribution section is meant to highlight the contribution of my research to existing literature. I will make it clearer when I incorporate it to my final paper.
